import argparse
import json
import os
import sys
from lxml import etree

_SUPPORTED_OPS = {"and", "or"}
_SKIP_OPS = {"not", "xor", "atleast"}

_SPECIAL_EVENTS = [
    {"id": "99999", "corrgate": "0", "name": "<TRUE>",
     "evworkspacepair": {"ph": 1, "mt": 1}, "value": 1.0,
     "initf": " ", "processf": " ", "calctype": "1"},
    {"id": "99998", "corrgate": "0", "name": "<FALSE>",
     "evworkspacepair": {"ph": 1, "mt": 1}, "value": 0.0,
     "initf": " ", "processf": " ", "calctype": "1"},
    {"id": "99997", "corrgate": "0", "name": "<PASS>",
     "evworkspacepair": {"ph": 1, "mt": 1}, "value": 1.0,
     "initf": " ", "processf": " ", "calctype": "1"},
    {"id": 99996, "corrgate": "0", "name": "AUTOGENERATED",
     "evworkspacepair": {"ph": 1, "mt": 1}, "value": 1.0,
     "initf": "I", "processf": " ", "calctype": "N"},
]


def _strip_ns(tag):
    return tag.split("}")[-1] if "}" in tag else tag


def convert(xml_path: str, output_path: str, cutoff: float = 1e-12) -> bool:
    try:
        tree = etree.parse(xml_path, etree.XMLParser(recover=True))
    except Exception:
        return False

    root = tree.getroot()

    for elem in root.iter():
        if _strip_ns(elem.tag) in _SKIP_OPS:
            return False

    event_probs: dict[str, float] = {}
    for elem in root.iter():
        if _strip_ns(elem.tag) == "define-basic-event":
            name = elem.get("name")
            for child in elem:
                if _strip_ns(child.tag) == "float":
                    try:
                        event_probs[name] = float(child.get("value", 0.0))
                    except (TypeError, ValueError):
                        event_probs[name] = 0.0
                    break

    ft_elem = None
    for child in root:
        if _strip_ns(child.tag) == "define-fault-tree":
            ft_elem = child
            break
    if ft_elem is None:
        return False

    gate_defs: dict[str, dict] = {}
    gate_order: list[str] = []

    for dg in ft_elem:
        if _strip_ns(dg.tag) != "define-gate":
            continue
        gate_name = dg.get("name")
        gate_order.append(gate_name)
        for op_elem in dg:
            op_type = _strip_ns(op_elem.tag)
            if op_type in _SKIP_OPS:
                return False
            if op_type not in _SUPPORTED_OPS:
                continue
            children = []
            for child in op_elem:
                child_tag = _strip_ns(child.tag)
                if child_tag in _SKIP_OPS:
                    return False
                if child_tag == "gate":
                    children.append(("gate", child.get("name")))
                elif child_tag == "basic-event":
                    children.append(("event", child.get("name")))
            gate_defs[gate_name] = {"type": op_type, "children": children}
            break

    if not gate_defs:
        return False

    referenced_gates: set[str] = set()
    for gd in gate_defs.values():
        for kind, name in gd["children"]:
            if kind == "gate":
                referenced_gates.add(name)

    top_gate = None
    for gname in gate_order:
        if gname not in referenced_gates:
            top_gate = gname
            break
    if top_gate is None:
        return False

    _TOP_GATE_ID = 80000
    gate_id_map: dict[str, int] = {}
    event_id_map: dict[str, int] = {}
    child_gate_counter = [1]
    event_counter = [0]
    gatelist: list[dict] = []

    def _next_child_gate():
        child_gate_counter[0] += 1
        return child_gate_counter[0]

    def _next_event():
        event_counter[0] += 1
        return event_counter[0]

    def _visit(gate_name: str) -> int:
        if gate_name in gate_id_map:
            return gate_id_map[gate_name]
        if not gate_id_map:
            gid = _TOP_GATE_ID
        else:
            gid = _next_child_gate()
        gate_id_map[gate_name] = gid
        gdef = gate_defs.get(gate_name)
        if gdef is None:
            return gid
        gate_inputs: list[int] = []
        event_inputs: list[int] = []
        for kind, cname in gdef["children"]:
            if kind == "gate":
                gate_inputs.append(_visit(cname))
            else:
                if cname not in event_id_map:
                    event_id_map[cname] = _next_event()
                event_inputs.append(event_id_map[cname])
        entry: dict = {
            "gateid": gid,
            "gatetype": gdef["type"],
            "numinputs": len(gate_inputs) + len(event_inputs),
        }
        if gate_inputs:
            entry["gateinput"] = gate_inputs
        if event_inputs:
            entry["eventinput"] = event_inputs
        gatelist.append(entry)
        return gid

    top_gate_id = _visit(top_gate)
    top_entry = next(g for g in gatelist if g["gateid"] == top_gate_id)
    gatelist.remove(top_entry)
    gatelist.insert(0, top_entry)
    num_gates = len(gatelist)
    num_basic_events = len(event_id_map)

    basic_events = [
        {
            "id": eid,
            "corrgate": 0,
            "name": ename,
            "evworkspacepair": {"ph": 1, "mt": 1},
            "value": event_probs.get(ename, 0.0),
            "initf": " ",
            "processf": " ",
            "calctype": "1",
        }
        for ename, eid in sorted(event_id_map.items(), key=lambda x: x[1])
    ]

    _FT_ID = 139

    jsinp = {
        "version": "1.0",
        "saphiresolveinput": {
            "header": {
                "projectpath": "",
                "eventtree": {"name": "", "number": 0, "initevent": 0, "seqphase": 1},
                "flagnum": 0,
                "ftcount": 1,
                "fthigh": _FT_ID,
                "sqcount": 0,
                "sqhigh": 0,
                "becount": num_basic_events + len(_SPECIAL_EVENTS),
                "behigh": 99996,
                "mthigh": 1,
                "phhigh": 1,
                "truncparam": {
                    "ettruncopt": "NormalProbCutOff",
                    "fttruncopt": "GlobalProbCutOff",
                    "sizeopt": "ENoTrunc",
                    "ettruncval": cutoff,
                    "fttruncval": cutoff,
                    "sizeval": 99,
                    "transrepl": False,
                    "transzones": False,
                    "translevel": 0,
                    "usedual": False,
                    "dualcutoff": 0.0,
                },
                "workspacepair": {"ph": 1, "mt": 1},
                "iworkspacepair": {"ph": 1, "mt": 1},
            },
            "sysgatelist": [
                {
                    "name": "Autogenerated",
                    "id": _FT_ID,
                    "gateid": top_gate_id,
                    "gateorig": top_gate_id,
                    "gatepos": 0,
                    "eventid": 99996,
                    "gatecomp": top_gate_id,
                    "comppos": 0,
                    "compflag": " ",
                    "gateflag": " ",
                    "gatet": " ",
                    "bddsuccess": False,
                    "done": False,
                }
            ],
            "faulttreelist": [
                {
                    "ftheader": {
                        "ftid": _FT_ID,
                        "gtid": top_gate_id,
                        "evid": 99996,
                        "defflag": 0,
                        "numgates": num_gates,
                    },
                    "gatelist": gatelist,
                }
            ],
            "eventlist": _SPECIAL_EVENTS + basic_events,
        },
    }

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(jsinp, f, indent=4)

    return True


def main():
    parser = argparse.ArgumentParser(
        description="Convert OpenPSA XML fault tree to SAPHSOLVE JSInp format"
    )
    parser.add_argument("input", help="Path to OpenPSA XML file")
    parser.add_argument("output", help="Path to output .JSInp file")
    parser.add_argument(
        "--cutoff", type=float, default=1e-12,
        help="MCS probability truncation cutoff (default: 1e-12)"
    )
    args = parser.parse_args()

    ok = convert(args.input, args.output, args.cutoff)
    if not ok:
        print(f"SKIP: {args.input} (unsupported gate types or parse error)", file=sys.stderr)
        sys.exit(1)
    print(f"OK: {args.output}")


if __name__ == "__main__":
    main()
